name: CI/CD Deploy FE to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_PROD }}" > .env.production

      - name: Build FE
        run: |
          npm ci
          npm run build

      - name: Clean old FE build on VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "ðŸ§¹ Removing old FE dist folder..."
            rm -rf /home/root/FE/dist
            mkdir -p /home/root/FE/dist

      - name: Upload new dist to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist"
          target: "/home/root/FE"

      - name: Restart nginx container
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/root/nginx
            docker compose restart nginx
